### ISSUE TITLE
请问是用的Mono.Cecil.Pdb.dll 放到工程中报错

### ISSUE THREAD

**Issue by absir** [Tencent/xLua#6]
用的Unity5.4安装目录下的
报一下错误 Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded

**Comment by chexiongsheng** [comment]
你试试删了看看？某些版本不用放到工程目录，放了反而会冲突。

**Comment by absir** [comment]
删除会有类似的依赖错误， “Assets/XLua/Src/Editor/Hotfix.cs(312,58): error CS1502: The best overloaded method match for `Mono.Cecil.GenericArgumentCollection.Add(Mono.Cecil.TypeReference)' has some invalid arguments；”
您现在项目中的使用的Mono.Cecil.Pdb.dll， 可以共享一份出来 我试下吗， 谢谢了

**Comment by chexiongsheng** [comment]
我是基于5.2.3开发的，我试试5.4，可能5.4配套的cecil升级了，api有变动。
你是window的unity么？
拷贝给你可能会和5.4的有冲突。
解决之前如果你想体验，可以用Unity 5.2.3来试试。

**Comment by absir** [comment]
谢谢了，我先用5.2.3试下。 我这边mac下的5.4 和 5.2.4试了都不行； 用同事window下的5.4 也不行

**Comment by chexiongsheng** [comment]
我刚刚mac下用5.4.1f1试过时可以的
在Assets/XLua/Src/Editor下执行
cp /Applications/Unity/Unity.app/Contents/Managed/Mono.Cecil.* .
然后就可以了。

**Comment by cg0206** [comment]
用window版5.5.0f2 unity，
报错“InvalidOperationException: Operation is not valid due to the current state of the object
System.Linq.Enumerable.Single[MethodDefinition] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
System.Linq.Enumerable.Single[MethodDefinition] (IEnumerable`1 source, System.Func`2 predicate)
XLua.Hotfix.init (Mono.Cecil.AssemblyDefinition assembly) (at Assets/XLua/Src/Editor/Hotfix.cs:45)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:136)”

**Comment by chexiongsheng** [comment]
@cg0206 是直接clone XLua，没加任何东西么？还是放到你们项目对你们自己的类打了Hotfix标签？

**Comment by cg0206** [comment]
@chexiongsheng
1、,先建一个工程
2、直接clone xlua asset文件夹
3、添加mono.ceil.*
4、运行项目中的hotfixTest例子，然后就报错了。

**Comment by chexiongsheng** [comment]
@cg0206 要等打印了hotfix inject finish!日志才运行。
还有，热补丁依赖代码生成，你要执行“XLua/Generate Code”菜单。
要重新触发补丁注入，你要触发编译，随便改改代码，然后等编辑器打印“hotfix inject finish!”了，才去运行程序。

**Comment by cg0206** [comment]
@chexiongsheng 触发编译之后，
编译时报错“InvalidOperationException: Operation is not valid due to the current state of the object
System.Linq.Enumerable.Single[MethodDefinition] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
System.Linq.Enumerable.Single[MethodDefinition] (IEnumerable`1 source, System.Func`2 predicate)
XLua.Hotfix.init (Mono.Cecil.AssemblyDefinition assembly) (at Assets/XLua/Src/Editor/Hotfix.cs:45)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:137)”

**Comment by chexiongsheng** [comment]
@cg0206 谢谢反馈！我们尽快处理。

**Comment by cg0206** [comment]
@chexiongsheng 找到问题了，谢谢耐心的解答

**Comment by chexiongsheng** [comment]
@cg0206 啥原因啊？分享下！我看是不是要放faq上。

出于人力的问题，我们不太可能做到把所有unity版本都下载试一趟的。

**Comment by cg0206** [comment]
@chexiongsheng unity5.5.0f2(64-bit)、unity5.4.2f2(64-bit)这两个版本这两个版本都是好的

**Comment by chexiongsheng** [comment]
@cg0206 十分感谢！

**Comment by qwq123qa** [comment]
@cg0206  @chexiongsheng      感谢...........在5.5.0p3 版本中也好的

**Comment by chexiongsheng** [comment]
@absir 你那可以了么？我试过5.4.1f1可以。楼上一些童鞋unity5.5.0f2(64-bit)、unity5.4.2f2(64-bit)，5.5.0p3 都反馈是OK的，其中有一个是因为宏设置方法导致的问题，你可以看看能解决你的问题不。

**Comment by chexiongsheng** [comment]
@absir 你把Mono.Cecil.mdb.dll也拷贝进项目试试看？

**Comment by michaelpengcn** [comment]
亲，我是MAC5.4.x， 可以正常运行，拷贝cecil的时候有dll, mdb,pdb三个文件。我同事是windows， 拷贝的时候只有dll， 然后就报了 Assets/XLua/Src/Editor/Hotfix.cs(171,72): error CS0122: `Mono.Cecil.MethodReference.ContainsGenericParameter' is inaccessible due to its protection level
。是不是忘记提交另外两个文件了，亲？

**Comment by chexiongsheng** [comment]
@michaelpengcn 这是老版本cecil的ContainsGenericParamete字段是internal的缘故，已经做了兼容，请更新下代码。

**Comment by michaelpengcn** [comment]
是的，methodReference接口变了，我刚要改，你太快了。赞一个

**Comment by chexiongsheng** [comment]
@michaelpengcn 刚好机器上安装了4.7.2，另外一个issues反馈的就是这版本。。否则没那么快。
比较烦的是，这类兼容问题很难前期发现，我不太可能把所有版本都安装了试。

**Comment by michaelpengcn** [comment]
这套东西支持il2cpp吗？

**Comment by chexiongsheng** [comment]
@michaelpengcn 支持
